// Code generated by dagger. DO NOT EDIT.
const DEFAULT_IMAGE_REF = "ghcr.io/gerhard/engine:v0.3.6-alpha.2@sha256:b286ba5909b5e7d14ed222fde299790a79ad665eaaefe4cb679081f54a63acd8";

export const DEFAULT_HOST = `docker-image://${DEFAULT_IMAGE_REF}`
