// Code generated by dagger. DO NOT EDIT.
const DEFAULT_IMAGE_REF = "ghcr.io/gerhard/engine:v0.3.6-alpha.1@sha256:738891d02bdc4247971b6c80a663b86db801014d367afb175e4f5ec2537c8980";

export const DEFAULT_HOST = `docker-image://${DEFAULT_IMAGE_REF}`
