project_name: dagger-cue

monorepo:
  tag_prefix: sdk/cue/

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/dagger
    binary: dagger-cue
    ldflags:
      - -s -w
      - -X go.dagger.io/dagger/version.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    files:
      - LICENSE
      - examples/**/*
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^doc:"
      - "^test:"
      - "^tests:"
      - "^ci:"
      - "^website:"
      - "^infra:"
      - "^chore:"
      - "^build\\(deps\\):"
      - "^build\\(deps-dev\\):"
      - "^Merge pull request"
  groups:
    - title: Breaking Changes
      regexp: "^.*!:+.*$"
      order: 0
    - title: Changes
      order: 999

# https://goreleaser.com/customization/homebrew/
brews:
  - tap:
      owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
      name: homebrew-tap
    name: dagger-cue
    commit_author:
      name: dagger-bot
      email: noreply@dagger.io
    url_template: "https://{{ .Env.ARTEFACTS_FQDN }}/dagger-cue/releases/{{ .Version }}/{{ .ArtifactName }}"
    homepage: "https://github.com/dagger/dagger"
    description: "Dagger is a programmable deployment system."
    test: |
      system "#{bin}/dagger-cue version"

blobs:
  - provider: s3
    region: "{{ .Env.AWS_REGION }}"
    bucket: "{{ .Env.AWS_BUCKET }}"
    folder: "dagger-cue/releases/{{ .Version }}"

publishers:
  - name: publish-latest-version
    cmd: sh -c "echo {{ .Version }} | aws s3 cp - s3://{{ .Env.AWS_BUCKET }}/dagger-cue/latest_version"
    env:
      - PATH={{ .Env.PATH }}
      - AWS_EC2_METADATA_DISABLED=true
      - AWS_ACCESS_KEY_ID={{ .Env.AWS_ACCESS_KEY_ID }}
      - AWS_SECRET_ACCESS_KEY={{ .Env.AWS_SECRET_ACCESS_KEY }}
      - AWS_REGION={{ .Env.AWS_REGION }}
  - name: publish-latest
    cmd: sh -c "echo {{ .Version }} | aws s3 cp - s3://{{ .Env.AWS_BUCKET }}/dagger-cue/versions/latest"
    env:
      - PATH={{ .Env.PATH }}
      - AWS_EC2_METADATA_DISABLED=true
      - AWS_ACCESS_KEY_ID={{ .Env.AWS_ACCESS_KEY_ID }}
      - AWS_SECRET_ACCESS_KEY={{ .Env.AWS_SECRET_ACCESS_KEY }}
      - AWS_REGION={{ .Env.AWS_REGION }}
  - name: publish-latest-major-minor
    cmd: sh -c "echo {{ .Version }} | aws s3 cp - s3://{{ .Env.AWS_BUCKET }}/dagger-cue/versions/{{ .Major }}.{{ .Minor }}"
    env:
      - PATH={{ .Env.PATH }}
      - AWS_EC2_METADATA_DISABLED=true
      - AWS_ACCESS_KEY_ID={{ .Env.AWS_ACCESS_KEY_ID }}
      - AWS_SECRET_ACCESS_KEY={{ .Env.AWS_SECRET_ACCESS_KEY }}
      - AWS_REGION={{ .Env.AWS_REGION }}

# We do not want to publish dagger-cue as a GitHub release until we have clarified the other SDKs
release:
  disable: true
